title: Cassio's Blog
email: cassio.dias.25@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Whatever I'm thinking about or working on. It can be a story, research, language, book or a joke. Hopefully other people will find them helpful.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://cassiodias.github.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: cassiodias25
github_username:  cassiodias

# Build settings
theme: minima
plugins:
  - jekyll-feed

port: 4445    
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google Analytics
google_analytics: UA-27249299-1
