apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: cassio-test
  name: cassio-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassio-test
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cassio-test
    spec:
      containers:
      - image: mongodb
        name: mongodb
        resources: {}
status: {}
